// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHQp3uhqQ3WBvVgrE6nFum7bdWpCxLjeo',
    appId: '1:804463104917:web:e2a00b3b0ef013009fdc9c',
    messagingSenderId: '804463104917',
    projectId: 'taskone-13006',
    authDomain: 'taskone-13006.firebaseapp.com',
    storageBucket: 'taskone-13006.firebasestorage.app',
    measurementId: 'G-DXPCPV423C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1ksr1x3ubPYdOIZZaRJx5ZpweoJ5EhA',
    appId: '1:804463104917:android:198052df24038ac99fdc9c',
    messagingSenderId: '804463104917',
    projectId: 'taskone-13006',
    storageBucket: 'taskone-13006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBD0bOzrOcfMJodg-zcXIxEYxClH3Ce8',
    appId: '1:804463104917:ios:bc7d5dc03d2c6efd9fdc9c',
    messagingSenderId: '804463104917',
    projectId: 'taskone-13006',
    storageBucket: 'taskone-13006.firebasestorage.app',
    iosBundleId: 'avs.com.taskone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBD0bOzrOcfMJodg-zcXIxEYxClH3Ce8',
    appId: '1:804463104917:ios:bc7d5dc03d2c6efd9fdc9c',
    messagingSenderId: '804463104917',
    projectId: 'taskone-13006',
    storageBucket: 'taskone-13006.firebasestorage.app',
    iosBundleId: 'avs.com.taskone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHQp3uhqQ3WBvVgrE6nFum7bdWpCxLjeo',
    appId: '1:804463104917:web:4db985cee8f64c149fdc9c',
    messagingSenderId: '804463104917',
    projectId: 'taskone-13006',
    authDomain: 'taskone-13006.firebaseapp.com',
    storageBucket: 'taskone-13006.firebasestorage.app',
    measurementId: 'G-42EGRLFELM',
  );

}